### ISSUE TITLE
Villager unusable

### ISSUE THREAD

**Issue by 909oce** [noah1510/EvenBetterArcheology#4]
Found an archeology villager tent, but whenever I try to trade, the window instantly closes so its impossible to interact with. This happens with all archeology villagers from my testing.

1.20.1 Fabric

Modlist:
3D Skin Layers
Advancement Plaques
AmbientSounds
Better Ping Display [Fabric]
CIT Resewn
CameraOverhaul
Clumps
Controlling
CreativeCore
Debugify
Diagonal Fences
Disable Custom Worlds Advice
Distant Horizons
FallingTree
Forge Config API Port
Forge Config Screens
Iceberg
ImmediatelyFast
ImmersiveThunder
Incendium
Legendary Tooltips
More Culling Extra
Nullscape
Presence Footsteps
Prism
Puzzles Lib
Searchables
Statement
Sunshine
SyncedAdvancements
Tax Free Levels
Terralith
Universal Bone Meal
Xaero's World Map
Xaero's Minimap
Zoomify
AdvancementInfo
AppleSkin
Architectury API
ARRP
Ash API
Balm
Better Block Sounds
Beautify: Refabricated
BetterPaths
Blur (Fabric)
Bobby
Bushier Flowers
Cave Dust
ClickThrough
Cloth Config API
Collective
Connectible Chains [Fabric]
Continuity
Cull Leaves
Dark Loading Screen
Deepslate Tweaks
Draggable Lists
Dynamic FPS
Dynamic Crosshair
Dynamic Crosshair Compat
Eating Animation
Elytra Slot
Enhanced Block Entities
[EMF] Entity Model Features
[ETF] Entity Texture Features
Entity Culling
Even Better Archeology
Exordium
Explosive Enhancement
ExtraSounds
Fabric API
Carpet
Fabric Language Kotlin
Fabric Seasons
Fabric Seasons: Terralith Compat
FabricSkyboxes
Fabrishot
Fadeless
Falling Leaves
FerriteCore
Ambient Fireflies
First-person Model
FormidableFarmland
Hidden Recipe Book
Highlight
Immersive Melodies
Indium
Inmis
InmisAddon
Interactic
Inventory Totem
Iris Shaders
JamLib
Just Enough Items
KleeSlabs
Krypton
LambDynamicLights
Librarian Trade Finder
Lithium
Make Bubbles Pop
Memory Leak Fix
MidnightLib
Model Gap Fix
ModernFix
Mod Menu
More Banner Features
More Culling
Mouse Wheelie
No Feeding Baby
No Hurt Cam
No Resource Pack Warnings
NoNarrator
Not Enough Animations
Nyf's Spiders
oωo (owo-lib)
Path Under Fence Gates
Physics Mod
playerAnimator
Raised
Reese's Sodium Options
RightClickHarvest
Screenshot to Clipboard
SeasonHUD-Fabric
Shuffle
Shulker Box Tooltip
Simple HUD Enhanced
Sodium Extra
Sodium
Soul Fire'd
Sound Physics Remastered
SuperMartijn642's Core Lib
SwingThrough
Tectonic
ThreadTweak
Tiny Item Animations
Too Many Binds
Trinkets
Video Tape
Visuality
Simple Voice Chat
way2wayfabric
Waystones
YetAnotherConfigLib

**Comment by 909oce** [comment]
Upon further testing, it seems this only happens on my server. The villager works fine in singleplayer.

**Comment by 909oce** [comment]
Okay sorry for another edit, I've just done some more testing as it's been a few days. It seems that the issue is with the villager generation. Naturally spawning villager tents seem to have an issue with assigning their profession so it just instant closes the menu, however breaking/replacing the workbench doesnt seem to fix it.

**Comment by 909oce** [comment]
https://github.com/noah1510/EvenBetterArcheology/assets/21692038/2ff0b2b1-eaa7-4ee2-ac56-e26c68431368

**Comment by noah1510** [comment]
Hi, which version of the mod do you use?

Also could you provide a log file?
With this Information there is not a lot I can do.
This problem does not happen on any of my machines.

Also did you try other villagers?
They might have the same problem.

**Comment by noah1510** [comment]
Never mind I think I found the problem.
The nbt structure data has the wrong id for the profession and has some offers set by default.
I changed so it should be fixed in 2.0.0-beta.6.
Could you try if that works for you too? It should fix all new villagers the old ones should still be broken.

**Comment by 909oce** [comment]
Fixed thank you!
